### ISSUE TITLE
Provide a sample code

### ISSUE THREAD

**Issue by lidoma** [mwienk/docker-lftp#2]
Hi,
Can you provide a .gitlab-ci.yml sample which used lftp docker service?

Thanks

**Comment by MattiJarvinen** [comment]
Came here to ask for the same thing.

**Comment by yugenekr** [comment]
That's what I have using this image

**Comment by yugaego** [comment]
That's what I have using this image for a very basic case

```
image: mwienk/docker-lftp:latest

stages:
  - deploy

deploy_production:
  stage: deploy
  script:

    - lftp -p 22 sftp://$USER:$PWD@$HOST -e "set ssl:verify-certificate no; set sftp:auto-confirm yes; mirror -Rnevp --parallel=10 --exclude-glob .git* --exclude .git/  --exclude-glob *.log --exclude log/ . /"

  only:
    - master
```

$USER and similar are GitLab CI variables.
